### ISSUE TITLE
First cropped image with wrong anchor position

### ISSUE THREAD

**Issue by andarilhoz** [yasirkula/UnityImageCropper#1]
Hi, using this plugin i noted taht the first cropped image gets wrong position, it takes some offset, or maybe somewhere in the middle of the image.

I tried to look at the source, and i do believe it is something inside the "CropSelection" function, but since i don't understand half of the stuff going on there, i couldn't get to anywhere.

After the first croped image, it works pretty well, it also happen in the Demo.

Reprodution steps:

- Open the demo;
- Try to crop the left bottom of the image;
- It will crop another place;

I tried mess with some options like pixelPerfect, but it didn't make any change to it.

**Comment by yasirkula** [comment]
I couldn't reproduce it on WebGL demo on _Chrome 67.0_ or _Firefox 60.0_. It always crops the correct part of the image for me. Can you post screenshots of your crop selection and the resulting displaced cropped image?

**Comment by andarilhoz** [comment]
Sorry for the delay.

I tested on the WebGL demo, and it doesn't seems to have the same problem, but i'm testing on Unity 2017.4.2f and i could reproduce it.

Open the scene in a new project:
![openedscene - unity 2017 4 2f2](https://user-images.githubusercontent.com/7517587/40919767-d64642c8-67e0-11e8-9fad-3e349a6df0a3.png)

Taking a screenshot:
![takedscreenshot](https://user-images.githubusercontent.com/7517587/40919768-d6722474-67e0-11e8-843c-0b571c7c347d.png)

Selecting a button part:
![selectedbuttonpart](https://user-images.githubusercontent.com/7517587/40919770-d69e8f46-67e0-11e8-9d9b-4d7ec767ffcb.png)

After clicking the crop button:
![aftercrop](https://user-images.githubusercontent.com/7517587/40919771-d6c78892-67e0-11e8-8a7f-79ceb2f0ca05.png)

If you think it will be helpfull i can make a video of it as well, also i'll try to take another look at the code.

Also, thank you for the reply 😄

**Comment by yasirkula** [comment]
I couldn't test it on 2017.4 because I don't have that version but I can verify that it works correctly on 2017.3.0p2 and 2018.1.3f1. Will keep you updated if I find something new.

**Comment by andarilhoz** [comment]
Today i tested on 2017.4.5f1, and it was perfectly fine!

i think there's something wrong with that unity version, thank you for your support!

i'll close this isssue (:
