### ISSUE TITLE
Image Download Issue

### ISSUE THREAD

**Issue by karanvariya** [yasirkula/UnityImageCropper#3]
I have issue with this plugin.
You plugin work with some pc.but some pc not work.

Issue In this Class File:
PickerController.cs

  private IEnumerator LoadImage(string path)
        {
            var url = "file://" + path;
            Debug.Log("Pick Url:" + url);
            var www = new WWW(url);
            yield return www;

//----------Error This Line---------------------

}

See My Console =
You are trying to load data from a www stream which had the following error when downloading.
Couldn't read a file:// file
UnityEngine.WWW:get_texture()
Kakera.<LoadImage>c__Iterator0:MoveNext() (at Assets/GallaryPicker/Unimgpicker/Samples/PickerController.cs:36)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Any Idea how to solve this bug???

Thanks in advance.

**Comment by yasirkula** [comment]
I'm not really sure why WWW fails like this but are you sure that this is related to the ImageCropper plugin? It seems more like it is related to the Unimgpicker plugin.

**Comment by karanvariya** [comment]
The Problem is my pc  starting path "file:///" work and another pc work "//".but my pc build for iOS not work.but android build work.

**Comment by yasirkula** [comment]
You should first check whether or not `File.Exists(path)` returns **true**. Maybe the file doesn't exist on iOS. Regardless, if this issue is related to the Unimgpicker plugin, I'd recommend you to open an issue in that repository to get better support from the author of that plugin.

**Comment by karanvariya** [comment]
File Already Exist in my pc path.and also show as picture view.
