### ISSUE TITLE
Feature Request: Image cropper displays an oval but the output's full rectangle is filled

### ISSUE THREAD

**Issue by michaelshum321** [yasirkula/UnityImageCropper#7]
Hi there,

When I use the Image Cropper where the selection is set to a circle, the output has the circle filled w/ the picture, and the outer portion is blacked out. 

Is there a Setting I can use so the outer portion is filled with the picture? So, even though the selection is an oval shape, the portion outside of the oval is filled with the original picture.

Thank you!

**Comment by yasirkula** [comment]
The black area is actually transparent. You are probably using the Texture on a non-transparent material. Regardless, to get a rectangular output, you can set OvalSelection to false at the beginning of this function: https://github.com/yasirkula/UnityImageCropper/blob/7613d0cdd6777aa994103d5c60362fc3c8027085/Plugins/ImageCropper/Scripts/ImageCropper.cs#L440

**Comment by michaelshum321** [comment]
yea, my usage is i'm saving the output of the cropper as a Jpeg, so transparency isn't available :( thanks for the the help! much appreciated
