### ISSUE TITLE
Not working with ngui

### ISSUE THREAD

**Issue by jpratik** [yasirkula/UnityImageCropper#8]
Hi, I am using it with ngui, it is working on unity editor but not working on android phone. I have tried to destroy ngui event listner by doing that it works but there is a catch it work after opening image cropper and closing it one time then work on android phone. Any suggestion how to make it work on android phone. (cropper rectangle not wroking on android, it doesn't move and touch not working while rotate button working fine)

**Comment by yasirkula** [comment]
Did you convert the plugin to NGUI, or does it still use Unity's UI system? In the latter case, did you make any modifications to the plugin?

**Comment by jpratik** [comment]
No I haven't convert plugin to ngui, let me explain in one scene I am using ngui for ui, in that scene I have used image cropper, that working fine on unity editor it shows on top of ngui ui and working well in unity editor and crops works well, but while testing on android phone the image cropper shows on top of any ui and button like rotate, crop, cancel works well but cropping rectangle doesn't work and even can't move rectangle or zoom in or out,
So spending lots of time I found that in ngui there is uicamera event system script on ngui camera if we disable it while beforeopening image cropper then image cropper rectangle works fine and can interact with rectangle and crop the desired image, but the problem is by doing this it won't work first time , it works on second time,so after one time open and close imagecropper second time imagecropper works, I have tried to open it with null texture so it may initialize its function but that also don't work , I think there is event system issue when we work with ngui, let me know how to overcome from it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yasirkula** [comment]
I have no experience with NGUI, unfortunately. The scripts related to moving and resizing the rectangle are these:

- https://github.com/yasirkula/UnityImageCropper/blob/master/Plugins/ImageCropper/Scripts/SelectionMovementHandler.cs
- https://github.com/yasirkula/UnityImageCropper/blob/master/Plugins/ImageCropper/Scripts/SelectionResizeHandler.cs

They use Unity's UI interfaces like IBeginDragHandler and IDragHandler. I don't know if these cause any incompatibilities with NGUI.

I'd recommend you to create a thread on NGUI's support forum and seek support from the author. Before that, you can try adding an EventSystem component to NGUI's UICamera object and see what happens.
